#!/usr/bin/env sh
# Copyright (C) 2023 Edes Istvan Gergely <edesig@gmail.com>. All Rights Reserved.
# This file is licensed under the MIT License.

readonly VERSION=0.1
DEBUG=${GIT_CREDENTIAL_PASS_DEBUG:-false}
readonly SECRET_PATH=${GIT_CREDENTIAL_SECRET_PATH:-git-credential-pass}

debug(){
	test "$DEBUG" = "false" || echo >&2 git-credential-pass:debug:$@
}

debug debug mode on
debug "called with:$@"
debug "stdin:$(cat -)"
eval set -- $(getopt -o i:s:b: -l identity: -l secret: -l blank: -- $@)
while true; do
	case "$1" in
		-s|--secret)
			SECRETS="${SECRETS:-} $2"
			shift 2
			continue ;;
		-b|--blank)
			BLANKS="${BLANKS:-} $2"
			shift 2
			continue ;;
		-i|--identity)
			IDENTITY="$2"
			shift 2
			continue ;;
		--)
			shift
			break ;;
	esac
done

case "$1" in
	get)
		for secret in $SECRETS; do
			echo "$secret=$(pass "$SECRET_PATH/$IDENTITY/$secret")";
		done
		for blank in $BLANKS; do
			echo "${blank}="
		done ;;
	store|erase)
		debug Not Implemented ;;
esac
echo quit=1
